swagger: "2.0"
info:
  title: "Name API"
  description: "Name API"
  version: "1.0.0"
host: "localhost:4020"
basePath: "/"
schemes:
- "http"
paths:
  /name:
    get:
      description: "Returns a random name"
      produces:
      - application/json
      responses:
        200:
          description: "request successful"
          schema:
            $ref: "#/definitions/Name"
  /nameage:
    get:
      description: "Returns a random name and age"
      produces:
      - application/json
      responses:
        200:
          description: "request successful"
          schema:
            $ref: "#/definitions/NameAge"
  /:
    get:
      description: Return 200 OK
      produces:
      - application/json
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Hello"
definitions:
  Name:
    type: "object"
    properties:
      FirstName:
        type: string
      LastName:
        type: string
  Age:
    type: "object"
    properties:
      Age:
        type: number
        minimum: 1
        maximum: 118
      YearBorn:
        type: number
        minimum: 1900
        maximum: 2018
  NameAge:
    type: "object"
    properties:
      Name:
        $ref: "#/definitions/Name"
      Age:
        $ref: "#/definitions/Age"
  Hello:
    type: "object"
    properties:
      Message:
        type: string
